# Generated by Django 3.2 on 2021-04-29 21:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('weight', models.IntegerField(verbose_name='weight')),
                ('vaccinated', models.BooleanField(verbose_name='vaccinated')),
            ],
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('completed', models.BooleanField(verbose_name='completed')),
            ],
        ),
        migrations.CreateModel(
            name='Forestry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=160, unique=True, verbose_name='title')),
                ('name_of_owner', models.CharField(max_length=100, verbose_name='name_of_owner')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('population', models.IntegerField(verbose_name='population')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('illness', models.CharField(max_length=100, verbose_name='illness')),
                ('animal_type', models.CharField(max_length=100, verbose_name='animal_type')),
                ('ml_in_dose', models.IntegerField(verbose_name='ml_in_dose')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestry.feeder')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestry.vaccine')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestry.animal')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestry.vaccine')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='feeder',
            name='forestry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestry.forestry'),
        ),
        migrations.AddField(
            model_name='animal',
            name='feeder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestry.feeder'),
        ),
    ]
