# Generated by Django 3.2 on 2021-05-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineset',
            name='feeder',
        ),
        migrations.RemoveField(
            model_name='vaccineset',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='vaccine',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
        migrations.DeleteModel(
            name='VaccineSet',
        ),
    ]
